[package]
name = "r2d2_control"
version = "0.1.0"
authors = ["jcweaver997 <jcweaver997@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = ""
gilrs = ""
